// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace BusinessObject.Entities;

public partial class Order
{
    [Required] 
    
    public int OrderId { get; set; }
    [Required]
    public int MemberId { get; set; }
    [Required]
    public DateTime OrderDate { get; set; }
    
    public DateTime? RequiredDate { get; set; }
    [Required]
    public DateTime? ShippedDate { get; set; }

    public decimal? Freight { get; set; }

    public virtual Member Member { get; set; }

    public virtual ICollection<OrderDetail> OrderDetails { get; set; } = new List<OrderDetail>();
}